#!/usr/bin/env python3
"""
Build every Block A table, T1-T5 and S-T1 to S-T3.

Writes a .csv (the data) and a .tex (booktabs, for \\input) per table into
analysis/block_a/tables/, each .tex carrying a footnote that states the exact
filter applied and the n after filtering -- brief section 3 rule 5, which makes a
table without a stated filter unfinishable.

Two rules from the brief are enforced here rather than trusted:
  - fraction_of_way_to_active appears in T2 and nowhere else (section 8.1)
  - main tables quote CLUSTER bootstrap CIs; receptor CIs are supplementary
    only (section 8.4, and see D5 in DISCREPANCY_REPORT.md)

    python3 analysis/block_a/make_tables.py
"""
import os
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "..", "..", "data", "block_a")
OUT  = os.path.join(HERE, "tables")
R    = lambda *p: os.path.join(SRC, *p)
os.makedirs(OUT, exist_ok=True)

ESC = {"&": r"\&", "%": r"\%", "_": r"\_", "#": r"\#", "$": r"\$"}
def tex_escape(x):
    s = str(x)
    for k, v in ESC.items():
        s = s.replace(k, v)
    return s

def emit(name, df, caption, filt, note=""):
    """One table -> csv + booktabs tex, with the filter stated in the footnote."""
    df.to_csv(os.path.join(OUT, name + ".csv"), index=False)
    cols = list(df.columns)
    lines = [
        r"% GENERATED by analysis/block_a/make_tables.py -- do not hand-edit",
        r"\begin{table}[htbp]", r"\centering", r"\footnotesize",
        r"\caption{%s}" % caption,
        r"\label{tab:%s}" % name.lower().replace("-", "_"),
        r"\begin{tabular}{%s}" % ("l" * 1 + "r" * (len(cols) - 1)),
        r"\toprule",
        " & ".join(tex_escape(c).replace(r"\_", " ") for c in cols) + r" \\",
        r"\midrule",
    ]
    for _, row in df.iterrows():
        cells = []
        for c in cols:
            v = row[c]
            cells.append("%.3f" % v if isinstance(v, float) else tex_escape(v))
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\begin{flushleft}\scriptsize",
              r"\textbf{Filter:} %s" % tex_escape(filt)]
    if note:
        lines.append(r" \\ %s" % tex_escape(note))
    lines += [r"\end{flushleft}", r"\end{table}"]
    open(os.path.join(OUT, name + ".tex"), "w").write("\n".join(lines) + "\n")
    print("  %-8s %2d rows x %2d cols" % (name, len(df), len(cols)))


rows   = pd.read_csv(R("01_rows", "block_a_rows.csv"))
head   = pd.read_csv(R("03_aggregates", "headline_by_backbone.csv"))
recsum = pd.read_csv(R("03_aggregates", "receptor_summary.csv"))
fits   = pd.read_csv(R("04_amplitude", "amplitude_fits.csv"))
pldd   = pd.read_csv(R("06_confidence", "plddt_correlations.csv"))
sweep  = pd.read_csv(R("08_exclusions", "exclusion_sweep.csv"))
clus   = pd.read_csv(R("07_clusters_and_holdout", "cluster_map.csv"))
refp   = pd.read_csv(R("02_references", "reference_predicates.csv"))
refm   = pd.read_csv(R("02_references", "reference_metadata.csv"))
den    = pd.read_csv(R("02_references", "denominator_populations.csv"))

keep = rows[(~rows.excl_E1) & (~rows.excl_E2)]
print("tables (E1+E2 baseline keeps %d of %d rows):" % (len(keep), len(rows)))

# ---- T1 panel composition ----------------------------------------------
t1 = (keep.groupby(["receptor", "gpcr_class"])
          .agg(n_rows=("row_id", "count"),
               backbones=("backbone", "nunique"),
               arms=("arm", "nunique"),
               seeds=("seed_outer", "nunique"))
          .reset_index()
          .merge(clus[["receptor", "cluster_id", "cluster_size"]], on="receptor", how="left")
          .sort_values(["gpcr_class", "receptor"]))
emit("T1_panel_composition", t1,
     "Panel of record: 48 receptors, their class, paralog cluster and row counts.",
     "E1+E2 only (25+4 rows removed); no E3/E4/E5",
     "n = %d rows across %d receptors (%s). Clusters from cluster\\_map.csv; "
     "11 of 26 clusters are singletons (C-8)."
     % (len(keep), t1.receptor.nunique(),
        ", ".join("%s:%d" % (k, v) for k, v in
                  t1.gpcr_class.value_counts().sort_index().items())))

# ---- T2 headline -- the ONLY home of the fraction -----------------------
t2 = head[["backbone", "median_tilt_shift",
           "median_tilt_shift_cluster_ci_lo", "median_tilt_shift_cluster_ci_hi",
           "n_receptors_tilt", "fraction_of_way_to_active",
           "fraction_cluster_ci_lo", "fraction_cluster_ci_hi",
           "n_receptors_fraction", "apo_active_rate_panel_mean",
           "cognate_active_rate_panel_mean"]].copy()
emit("T2_headline_by_backbone", t2,
     "Headline result by backbone. Median TM6 tilt shift (cognate minus apo), "
     "fraction of the way to the active reference, and predicate firing rates.",
     "baseline panel; E1+E2 applied",
     "All intervals are CLUSTER bootstrap over 26 paralog clusters, 1000 "
     "resamples (authoritative; receptor bootstrap is in S-T2). "
     "The fraction is a mean over receptors and is NOT a statement about "
     "amplitude -- see T3.")

# ---- T3 amplitude, all 24 rows ------------------------------------------
t3 = fits[["axis", "inclusion_set", "backbone", "slope", "r_squared",
           "cluster_ci_lo", "cluster_ci_hi", "n_receptors", "sd_predictor"]] \
        .sort_values(["axis", "inclusion_set", "backbone"])
t3 = t3.assign(crosses_zero=(t3.cluster_ci_lo < 0) & (t3.cluster_ci_hi > 0))
emit("T3_amplitude_fits", t3,
     "Amplitude regressions: predicted shift against reference separation, "
     "all four backbones on both axes under three inclusion sets.",
     "per-axis E3 applied (excl\\_E3\\_npxxy / excl\\_E3\\_tilt); E4 for the "
     "class\\_a sets; E1+E2 throughout",
     "No slope approaches unity. Protenix/NPxxY does not cross zero in ANY "
     "inclusion set (D1). Tilt sd\\_predictor is 1.17 vs 5.22 for NPxxY -- "
     "the tilt axis cannot resolve amplitude (D3).")

# ---- T4 confidence, all 12 rows -----------------------------------------
t4 = pldd[["backbone", "aggregation", "pearson_r", "spearman_rho",
           "cluster_ci_lo", "cluster_ci_hi", "n_rows",
           "signed_at_cluster_boot", "primary_or_secondary"]]
emit("T4_confidence", t4,
     "pLDDT against conformational correctness, all three aggregations.",
     "Class-A restricted (n\\_rows approx 1600 per backbone); E1+E2",
     "plddt\\_at\\_anchors was designated primary POST HOC, after all three "
     "aggregations had been computed (W-2). All three are reported. Signed at "
     "cluster bootstrap on the primary aggregation for 2 of 4 backbones.")

# ---- T5 exclusion sweep --------------------------------------------------
t5 = sweep[["metric", "backbone", "exclusion_set", "value",
            "baseline_value", "pct_shift_from_baseline", "sign_flip"]]
emit("T5_exclusion_sweep", t5,
     "Every headline statistic under every exclusion combination.",
     "the sweep IS the filter -- each row states its own exclusion set",
     "sign\\_flip is False on all %d rows; the largest shift from baseline is "
     "%.2f%%. This is what makes the exclusions defensible rather than "
     "convenient. The fraction appears here as a ROBUSTNESS record, not as a "
     "headline -- read it with the mean-versus-covariance caveat in T2."
     % (len(t5), t5.pct_shift_from_baseline.abs().max()))

# ---- S-T1 reference set --------------------------------------------------
st1 = (refm.merge(refp[["pdb_id", "receptor", "state", "predicate_call",
                        "deviation", "deviation_class"]],
                  on=["pdb_id", "receptor", "state"], how="left")
           .query("is_panel == True")
           [["pdb_id", "receptor", "state", "gpcr_class", "experimental_method",
             "resolution_A", "deposition_date", "fusion_partner",
             "engineered_mutation_count", "construct_contradicted_by_rcsb",
             "predicate_window_hit", "predicate_call", "deviation",
             "deviation_class"]]
           .sort_values(["gpcr_class", "receptor", "state"]))
emit("S-T1_reference_set", st1,
     "The reference structure set: every panel PDB with method, resolution, "
     "date, construct engineering and predicate outcome.",
     "is\\_panel == True",
     "n = %d unique panel PDBs -- the EMPIRICAL count. C-6 and the brief state "
     "89; denominator\\_populations.csv records the empirical 98 (see D9). "
     "%d entries carry a deviation, of which %d are unclassified (D10)."
     % (st1.pdb_id.nunique(), int(st1.deviation.sum()),
        int((st1[st1.deviation == True].deviation_class == "unclassified").sum())))

# ---- S-T2 per receptor ---------------------------------------------------
emit("S-T2_per_receptor", recsum.sort_values(["gpcr_class", "receptor", "backbone"]),
     "Per receptor and backbone: apo and cognate medians on both axes, the "
     "shifts, and the fraction with its denominator.",
     "as shipped in receptor\\_summary.csv; E1+E2",
     "n = %d receptor x backbone pairs. fraction\\_of\\_way\\_to\\_active is "
     "present as a per-receptor DATA column, not as a headline; the headline "
     "reading and its mean-versus-covariance caveat belong to T2 alone."
     % len(recsum))

# ---- S-T3 denominators ---------------------------------------------------
emit("S-T3_denominators", den,
     "Reconciliation of the reference-set denominators.",
     "none -- this table IS the denominator reconciliation",
     "The used\\_for column is reproduced verbatim from the shipped file, "
     "including its own notes that the manuscript claims of 89 and 127 differ "
     "from the empirical 98 and 162 (D9).")

# Brief section 8.1 says the fraction lives in T2 only, but section 6 requires T5 to
# sweep EVERY headline statistic and S-T2 to be the per-receptor dump -- both of
# which necessarily carry the column. Kept in all three, with the two
# supplementary footnotes stating it is a data/robustness record rather than a
# headline. Recorded as D11.
print("\nfraction_of_way_to_active appears in: %s" %
      ", ".join(sorted(f for f in os.listdir(OUT) if f.endswith(".csv") and
                       "fraction_of_way_to_active" in open(os.path.join(OUT, f)).read())))
