# generated by render_struct.py on 2026-09-09T12:05:09 -- edit and re-run freely
reinitialize
bg_color white
set ray_opaque_background, 1
set antialias, 2
set orthoscopic, on
set ray_shadows, off
set ray_interior_color, grey70
set cartoon_fancy_helices, 1
set transparency_mode, 2
set specular, 0.15
set cartoon_sampling, 12
set surface_quality, 1
set label_size, 16
set label_color, black
set label_font_id, 7
set label_outline_color, white
set label_position, (0, 0, 2.5)
set depth_cue, 0
set ray_trace_mode, 0
set ray_trace_gain, 0.12
set ray_trace_color, grey20

load structures/3SN6.pdb, subject
hide everything
show cartoon, subject and polymer
color grey80, subject and polymer
set cartoon_transparency, 0.7, subject

# --- ligand and partners in front, fully opaque -------------------------
show sticks, subject and (chain R and resn P0G) and not hydrogens
color 0xD55E00, subject and (chain R and resn P0G) and elem C
util.cnc("subject and (chain R and resn P0G)")
set stick_radius, 0.13, subject and (chain R and resn P0G)


# --- residue labels -------------------------------------------
show sticks, subject and (chain R and resi 113) and sidechain and not hydrogens
label subject and (chain R and resi 113) and name CA, "%s%s" % (oneletter, resi)
show sticks, subject and (chain R and resi 203) and sidechain and not hydrogens
label subject and (chain R and resi 203) and name CA, "%s%s" % (oneletter, resi)
set label_position, (0,4,3), subject and (chain R and resi 203) and name CA

orient subject and (chain R and resn P0G)
zoom subject and (chain R and resn P0G), 9.0
ray 900, 700
png /Users/aditya/Documents/tools/Novartis_projects/paper/figures/out/demo_pocket.png, dpi=600
