#!/usr/bin/env python3
"""
make_si_tables.py — supplementary tables for Blocks B, C and D.

Block A's tables come from analysis/block_a/make_tables.py. Blocks B, C and D had no
generator, so their results appeared in no table anywhere. This fills that gap and writes
S-T4..S-T8 into this directory. Reads data/block_*/ read-only; writes only S-T[4-8]*.tex.

    python3 manuscript/tables/make_si_tables.py

Every table states its filter and its n, matching the SI convention. Where a shipped
number and a recomputed one disagree, both are printed — the disagreement is the content.
"""
import os, json, re
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
D = os.path.join(ROOT, "data")
OUT = os.path.dirname(os.path.abspath(__file__))
BB = ["boltz", "chai", "of3", "protenix"]
NICE = {"boltz": "Boltz-2", "chai": "Chai-1", "of3": "OpenFold-3", "protenix": "Protenix"}
# The Block D table copies claim-sheet headlines verbatim, and those carry Unicode that
# pdflatex will not accept. Map it rather than strip it: the symbols are load-bearing.
_UNI = {
    "\u2265": r"$\geq$", "\u2264": r"$\leq$", "\u00d7": r"$\times$", "\u00b1": r"$\pm$",
    "\u03b1": r"$\alpha$", "\u03b2": r"$\beta$", "\u03c4": r"$\tau$", "\u03bc": r"$\mu$",
    "\u0394": r"$\Delta$", "\u03c1": r"$\rho$", "\u00c5": r"\AA{}", "\u00b0": r"$^\circ$",
    "\u2013": "--", "\u2014": "---", "\u2192": r"$\rightarrow$", "\u2248": r"$\approx$",
    "\u2019": "'", "\u201c": "``", "\u201d": "''", "\u2026": r"\ldots{}", "\u00a0": " ",
}


def esc(s):
    s = str(s)
    for u, t in _UNI.items():
        s = s.replace(u, t)
    s = s.replace("_", r"\_").replace("%", r"\%").replace("&", r"\&").replace("#", r"\#")
    # anything still non-ASCII would break the build; drop it loudly rather than silently
    return "".join(ch if ord(ch) < 128 else "?" for ch in s)


def wrap(body, caption, label, filt, note=""):
    return (
        "% GENERATED by manuscript/tables/make_si_tables.py -- do not hand-edit\n"
        "\\begin{table}[htbp]\n\\centering\n\\footnotesize\n"
        f"\\caption{{{caption}}}\n\\label{{{label}}}\n{body}\n"
        "\\begin{flushleft}\\scriptsize\n"
        f"\\textbf{{Filter:}} {filt}" + (f" \\\\ {note}" if note else "") +
        "\n\\end{flushleft}\n\\end{table}\n")


def t4_ladder():
    f = pd.read_csv(os.path.join(D, "block_b/04_ladder/ladder_four_scorings.csv"))
    FR = [x for x in ["all_40", "reproduction_36"] if x in set(f.frame)]
    rows = []
    for fr in FR:
      fsub = f[f.frame == fr]
      rows.append(r"\multicolumn{6}{l}{\textit{frame " + esc(fr) + r"}} \\")
      for arm in ["apo", "decoy", "shuffled", "cognate"]:
        a = fsub[fsub.arm == arm]
        if a.empty:
            continue
        cells = []
        for b in BB:
            r = a[a.backbone == b]
            cells.append(f"{r.binary_predicate.iloc[0]:.3f} [{r.cluster_boot_ci_lo_binary.iloc[0]:.3f}, "
                         f"{r.cluster_boot_ci_hi_binary.iloc[0]:.3f}]" if len(r) else "--")
        rows.append(f"\\quad {esc(arm)} & {int(a.n_rows.mean())} & " + " & ".join(cells) + r" \\")
    body = ("\\begin{tabular}{lr" + "l" * len(BB) + "}\n\\toprule\narm & $n$ rows & "
            + " & ".join(NICE[b] for b in BB) + r" \\" + "\n\\midrule\n" + "\n".join(rows)
            + "\n\\bottomrule\n\\end{tabular}")
    return wrap(body, "The four-arm co-input ladder: two-instrument active-call fraction "
                "by arm and backbone, with cluster-bootstrap 95\\% intervals.",
                "stab:ladder", "both shipped frames; $n$ rows per arm shown.",
                "Every arm supplies a complete G$\\alpha$ subunit of 350--394 residues. No arm supplies "
                "a peptide. The decoy arm is the correct subunit with its eleven C-terminal residues "
                "permuted; the shuffled arm is a different G$\\alpha$ class carrying its own native "
                "$\\alpha$5 C-terminus.")


def t5_decomposition():
    d = pd.read_csv(os.path.join(D, "block_b/05_decomposition/ladder_decomposition.csv"))
    lad = pd.read_csv(os.path.join(D, "block_b/04_ladder/ladder_four_scorings.csv"))
    FR = [x for x in ["all_40", "reproduction_36"] if x in set(d.frame)]
    rows = []
    for fr in FR:
      dfr = d[(d.frame == fr) & (d.scale == "probability")]
      lfr = lad[lad.frame == fr]
      rows.append(r"\multicolumn{6}{l}{\textit{frame " + esc(fr) + r"}} \\")
      for b in BB:
        db, lb = dfr[dfr.backbone == b], lfr[lfr.backbone == b]
        get = lambda arm: (lb[lb.arm == arm].binary_predicate.iloc[0] if len(lb[lb.arm == arm]) else float("nan"))
        occ = db[db.contrast.str.contains("occupancy")]
        fam = db[db.contrast.str.contains("correct_family")]
        conf = db[db.contrast.str.contains("a5ct_sequence")]
        rows.append(
            f"\\quad {NICE[b]} & {occ.term_estimate.iloc[0]:.3f} & {get('cognate')-get('decoy'):+.3f} & "
            f"{fam.term_estimate.iloc[0]:.3f} & {conf.term_estimate.iloc[0]:.3f} & "
            f"{get('cognate')-get('apo'):.3f}" + r" \\")
    body = ("\\begin{tabular}{lrrrrr}\n\\toprule\nbackbone & occupancy & "
            "\\textbf{$\\alpha$5-CT} & correct family & \\textit{(confounded)} & total \\\\\n"
            " & apo$\\rightarrow$decoy & \\textbf{decoy$\\rightarrow$cognate} & "
            "shuffled$\\rightarrow$cognate & decoy$\\rightarrow$shuffled & apo$\\rightarrow$cognate \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    return wrap(body, "Decomposition of the ladder, restated. The clean $\\alpha$5-CT contrast is "
                "\\textbf{decoy$\\rightarrow$cognate}: identical scaffold, identical length, identical "
                "G$\\alpha$ family, only the eleven C-terminal residues differ.",
                "stab:decomposition",
                "both shipped frames, probability scale.",
                "The column marked \\textit{(confounded)} is the shipped "
                "\\texttt{delta\\_a5ct\\_sequence\\_decoy\\_to\\_shuffled} term. It is arithmetically "
                "correct and interpretively confounded: decoy$\\rightarrow$shuffled exchanges roughly "
                "349 of 359 residues plus length, family and the partner's alignment, so it cannot be "
                "attributed to the $\\alpha$5 C-terminus. It is printed here so the restatement is "
                "auditable rather than silent. Occupancy and $\\alpha$5-CT telescope exactly to the total.")


def t6_classifier():
    """Print BOTH bootstraps. Which resampling unit was used has been mis-stated three times
    on this project (a row bootstrap labelled receptor-boot, a cluster CI quoted as receptor),
    so the table shows both and names the file's own authoritative convention."""
    j = json.load(open(os.path.join(D, "block_c/04_classifier/g1_bootstrap_s1_auroc.json")))
    conv = j.get("authoritative_convention", "not stated in file")
    rows = []
    for b in BB:
        s = j["per_backbone"].get(b)
        if not s:
            continue
        au = s["observed_pooled_auroc"]
        rb, cb = s["receptor_boot"]["ci_95"], s["cluster_boot"]["ci_95"]
        nclust = s["cluster_boot"].get("n_clusters", "--")
        spans = "\\textbf{yes}" if cb[0] <= 0.5 else "no"
        rows.append(f"{NICE[b]} & {au:.3f} & [{rb[0]:.3f}, {rb[1]:.3f}] & "
                    f"[{cb[0]:.3f}, {cb[1]:.3f}] & {nclust} & {spans}" + r" \\")
    body = ("\\begin{tabular}{lrllcc}\n\\toprule\nbackbone & AUROC & receptor-boot 95\\% CI & "
            "cluster-boot 95\\% CI & clusters & cluster CI spans 0.5 \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    return wrap(body, "Leave-one-receptor-out classification of ligand class, by backbone, under "
                "both resampling conventions.",
                "stab:classifier",
                f"as shipped, 15 receptors; file's authoritative convention: \\texttt{{{esc(conv)}}}.",
                "Both bootstraps are printed because the resampling unit has been mis-stated more than "
                "once on this project. The split itself is by receptor, verified: an AUROC of 0.000 on "
                "a held-out receptor is impossible under a structure-level split. Under the cluster "
                "convention two of four backbones span 0.5 and are not evidence of separation. A "
                "residual caveat the intervals do not capture: paralogs are divided across folds while "
                "the interval treats the paralog cluster as the independent unit.")


def t7_blockd():
    """Block D ships NO row-level data — all three named corpora are absent and the five
    shipped CSVs are panel metadata. So its results appear in no table anywhere unless one
    is built from the claim sheet itself. This is that table, and it is explicitly a
    coverage map, not a results table."""
    src = os.path.join(D, "block_d/01_claims/BLOCK_D_CLAIM_SHEET.md")
    txt = open(src).read()
    tier, rows = "--", []
    for line in txt.split("\n"):
        t = re.match(r"^##\s+(D\d) tier", line.strip())
        if t:
            tier = t.group(1)
        if line.strip().startswith("## D-tier cross-cutting"):
            tier = "cross"
        m = re.match(r"^-\s+\*\*(SC-D-\d+)\*\*\s*[—-]\s*(.*)$", line.strip())
        if m:
            head = re.sub(r"\*\*|`", "", m.group(2))
            head = " ".join(head.split())
            head = head[:118] + ("..." if len(head) > 118 else "")
            rows.append(f"{esc(m.group(1))} & {tier} & {esc(head)}" + r" \\")
    if not rows:
        return None
    body = ("\\begin{tabular}{llp{10.6cm}}\n\\toprule\nclaim & tier & headline as stated in the "
            "claim sheet \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    return wrap(body,
        "Block~D claim coverage. \\textbf{This is a coverage map, not a results table.}",
        "stab:blockd_coverage",
        "the shipped claim sheet, verbatim headlines.",
        "\\textbf{Block~D ships no row-level data.} All three corpora its claim sheet names "
        "(D1 14{,}000, D2 2{,}370 and D3 25{,}810 predictions) are referenced by path and are "
        "absent from the archive; the five shipped CSVs are panel metadata. Twelve of twelve "
        "claims are therefore prose-only in whole or in part, and what could be recomputed was "
        "recomputed from summary statistics and from deposited coordinates rather than from rows: "
        "all six Clopper--Pearson intervals reproduce exactly at $n = 50$, D3's 22 clusters over 26 "
        "receptors reproduce, and Tyr\\,7.53 was located independently from each file's own NPxxY "
        "motif in all fifteen shipped structures, agreeing with the database-mapped position in "
        "every case. No Block~D claim carries a main-text figure for this reason.")


def main():
    written = []
    for fn, name in [(t4_ladder, "S-T4_ladder"), (t5_decomposition, "S-T5_decomposition")]:
        try:
            open(os.path.join(OUT, name + ".tex"), "w").write(fn()); written.append(name)
        except Exception as e:
            print(f"  !! {name}: {e}")
    try:
        tex = t7_blockd()
        if tex:
            open(os.path.join(OUT, "S-T7_blockd_coverage.tex"), "w").write(tex)
            written.append("S-T7_blockd_coverage")
    except Exception as e:
        print(f"  !! S-T7_blockd_coverage: {e}")
    try:
        res = t6_classifier()
        tex = res[0] if isinstance(res, tuple) else res
        if tex:
            open(os.path.join(OUT, "S-T6_classifier.tex"), "w").write(tex); written.append("S-T6_classifier")
        else:
            print("  !! S-T6: classifier JSON shape unrecognised; sample:", res[1])
    except Exception as e:
        print(f"  !! S-T6_classifier: {e}")
    print("wrote:", ", ".join(written) if written else "nothing")


if __name__ == "__main__":
    main()
