#!/usr/bin/env python3
"""
Publication structure renders, driven from the command line.

The house scene: the protein as a pale, semi-transparent cartoon sitting in the
background, the ligand and any named residues in front as opaque sticks, and
residue numbers written next to them. Optionally a reference structure aligned
underneath in grey, which is what 232 of the corpus's render panels do.

It writes a .pml alongside the image. That file is the figure's source: open it
in the PyMOL GUI, nudge the camera, `get_view`, and paste the numbers back with
--view. Nothing here is a black box.

Every render also writes a .prov.json. That is deliberate. 81% of the structure
renders in our corpus carry a recorded defect, and the two commonest by a wide
margin are "hand-picked example, selection rule not stated" (59 panels) and
"no quantitative panel stands behind it" (58). A render that cannot say which
prediction it is, out of how many, and why that one, is the defect. So the
script refuses to run without --selected-from and --selection-rule.

Examples
--------
Pocket view, ligand plus three labelled residues:

  python3 render_struct.py --structure 3SN6.pdb --ligand "resn P0G" \\
      --label-residues "A/131+A/318+A/323" --zoom-on "resn P0G" \\
      --selected-from 1 --selection-rule "crystal structure, not a prediction" \\
      --out pocket

Prediction over reference, whole receptor:

  python3 render_struct.py --structure pred.pdb --reference 3SN6.pdb \\
      --align-on "chain R and polymer" --selected-from 250 \\
      --selection-rule "median d_tm6 of the cognate_ga arm" --out overlay
"""
import argparse, json, os, subprocess, sys, textwrap, datetime

HERE = os.path.dirname(os.path.abspath(__file__))

# Matches figstyle.PALETTE so renders and plots agree on what a colour means.
COLOURS = {
    "protein":   "grey80",
    "protein_vs_ref": "0x9EC4DC",   # pale blue, used only when a reference is drawn
    "reference": "grey60",
    "ligand":    "0xD55E00",   # vermillion
    "peptide":   "0x009E73",   # green
    "highlight": "0x0072B2",   # blue
    "label":     "black",
}

PML = """\
# generated by render_struct.py on {stamp} -- edit and re-run freely
reinitialize
bg_color white
set ray_opaque_background, {opaque_bg}
set antialias, 2
set orthoscopic, on
set ray_shadows, off
set ray_interior_color, grey70
set cartoon_fancy_helices, 1
set transparency_mode, 2
set specular, 0.15
set cartoon_sampling, 12
set surface_quality, 1
set label_size, {label_size}
set label_color, {c_label}
set label_font_id, 7
set label_outline_color, white
set label_position, (0, 0, 2.5)
set depth_cue, 0
set ray_trace_mode, {trace_mode}
set ray_trace_gain, 0.12
set ray_trace_color, grey20

load {structure}, subject
hide everything
show cartoon, subject and polymer
color {c_protein}, subject and polymer
set cartoon_transparency, {transparency}, subject
{reference_block}
# --- ligand and partners in front, fully opaque -------------------------
show sticks, subject and ({ligand}) and not hydrogens
color {c_ligand}, subject and ({ligand}) and elem C
util.cnc("subject and ({ligand})")
set stick_radius, 0.13, subject and ({ligand})
{peptide_block}
{highlight_block}
{label_block}
{extra}
{view_block}
ray {width}, {height}
png {png}, dpi={dpi}
"""

REFERENCE_BLOCK = """\
load {reference}, refstruct
hide everything, refstruct
show cartoon, refstruct and polymer
color {c_reference}, refstruct and polymer
set cartoon_transparency, {ref_transparency}, refstruct
align refstruct and ({align_on}), subject and ({align_on})
"""

PEPTIDE_BLOCK = """\
# its own object: cartoon_transparency is object-level, so an opaque partner
# in front of a transparent receptor cannot share one object with it
create partner, subject and ({peptide})
hide everything, partner
show cartoon, partner
color {c_peptide}, partner
set cartoon_transparency, 0, partner
hide cartoon, subject and ({peptide})
"""

HIGHLIGHT_BLOCK = """\
show sticks, subject and ({highlight}) and sidechain and not hydrogens
color {c_highlight}, subject and ({highlight}) and elem C
set stick_radius, 0.10, subject and ({highlight})
"""


def _split_specs(spec):
    """Split on commas, except those inside an @dx,dy,dz offset."""
    out, buf, in_off = [], "", False
    for ch in spec:
        if ch == "@":
            in_off = True
        if ch == "," and not in_off:
            out.append(buf); buf = ""; continue
        if ch == "," and in_off and buf.count(",", buf.index("@")) >= 2:
            in_off = False
            out.append(buf); buf = ""; continue
        buf += ch
    out.append(buf)
    return [s for s in (x.strip() for x in out) if s]


def label_block(spec, style):
    """
    Write residue labels.

    `spec` is a comma-separated list of selections. Any selection may carry a
    per-label offset as `selection@dx,dy,dz` — labels on neighbouring residues
    collide otherwise, and a collided label is unreadable, which is the same
    defect as no label at all.

        "chain A and resi 391@0,4,3, chain A and resi 392@0,-4,3"
    """
    if not spec:
        return ""
    fmt = {
        "number":   '"%s" % (resi)',
        "one":      '"%s%s" % (oneletter, resi)',
        "three":    '"%s%s" % (resn, resi)',
    }[style]
    lines = ["# --- residue labels -------------------------------------------"]
    for item in _split_specs(spec):
        item = item.strip()
        if not item:
            continue
        offset = None
        if "@" in item:
            item, off = item.split("@", 1)
            item = item.strip()
            nums = [p.strip() for p in off.split(";")] if ";" in off else None
            offset = off.strip()
        lines.append("show sticks, subject and (%s) and sidechain and not hydrogens"
                     % item)
        lines.append("label subject and (%s) and name CA, %s" % (item, fmt))
        if offset:
            lines.append("set label_position, (%s), subject and (%s) and name CA"
                         % (offset, item))
    return "\n".join(lines)


def build(args):
    ref = ""
    if args.reference:
        ref = REFERENCE_BLOCK.format(
            reference=args.reference, c_reference=COLOURS["reference"],
            ref_transparency=args.ref_transparency,
            align_on=args.align_on or "polymer and name CA")
    pep = ""
    if args.peptide:
        pep = PEPTIDE_BLOCK.format(peptide=args.peptide,
                                   c_peptide=COLOURS["peptide"])
    hi = ""
    if args.highlight:
        hi = HIGHLIGHT_BLOCK.format(highlight=args.highlight,
                                    c_highlight=COLOURS["highlight"])
    if args.view:
        view_block = "set_view (%s)" % args.view
    elif args.zoom_on:
        view_block = "orient subject and (%s)\nzoom subject and (%s), %.1f" % (
            args.zoom_on, args.zoom_on, args.zoom_buffer)
    else:
        view_block = "orient subject\nzoom subject, %.1f" % args.zoom_buffer

    return PML.format(
        stamp=datetime.datetime.now().isoformat(timespec="seconds"),
        opaque_bg=0 if args.transparent_background else 1,
        structure=args.structure, reference_block=ref, peptide_block=pep,
        highlight_block=hi,
        label_block=label_block(args.label_residues, args.label_style),
        ligand=args.ligand, transparency=args.transparency,
        label_size=args.label_size, trace_mode=args.trace_mode,
        c_protein=(COLOURS["protein_vs_ref"] if args.reference
                   else COLOURS["protein"]) if not args.protein_colour
                   else args.protein_colour, c_ligand=COLOURS["ligand"],
        c_label=COLOURS["label"], extra=args.extra or "",
        view_block=view_block, width=args.width, height=args.height,
        dpi=args.dpi, png=args.png)


def main():
    p = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=__doc__)
    p.add_argument("--structure", required=True, help="the model to draw")
    p.add_argument("--reference", help="a second structure, aligned and drawn in grey")
    p.add_argument("--align-on", help="selection used to superpose (default: CA)")
    p.add_argument("--ligand", default="organic",
                   help="selection drawn as opaque sticks (default: organic)")
    p.add_argument("--peptide", help="selection drawn as an opaque cartoon, e.g. the alpha5-CT chain")
    p.add_argument("--highlight", help="extra residues drawn as sticks but not labelled")
    p.add_argument("--label-residues",
                   help="comma-separated selections to label, e.g. 'chain A and resi 131,chain A and resi 391'")
    p.add_argument("--label-style", default="three",
                   choices=["number", "one", "three"],
                   help="what the label says: 131 / R131 / ARG131 (default: three)")
    p.add_argument("--label-size", type=float, default=16)
    p.add_argument("--transparency", type=float, default=0.70,
                   help="cartoon transparency of the background protein, 0-1 (default 0.72)")
    p.add_argument("--ref-transparency", type=float, default=0.85)
    p.add_argument("--zoom-on", help="selection to frame")
    p.add_argument("--zoom-buffer", type=float, default=4.0)
    p.add_argument("--view", help="an 18-number PyMOL view matrix from get_view")
    p.add_argument("--protein-colour", help="override the background cartoon colour")
    p.add_argument("--transparent-background", action="store_true",
                   help="RGBA output; only for compositing, not for LaTeX")
    p.add_argument("--trace-mode", type=int, default=0, choices=[0, 1, 2, 3],
                   help="0 plain, 1 black outlines (good for print)")
    p.add_argument("--width", type=int, default=2400)
    p.add_argument("--height", type=int, default=1800)
    p.add_argument("--dpi", type=int, default=600)
    p.add_argument("--extra", help="raw pml appended before the camera")
    p.add_argument("--out", required=True, help="output stem")
    p.add_argument("--outdir", default=os.path.join(HERE, "out"))
    # provenance, and it is not optional
    p.add_argument("--selected-from", type=int, required=True,
                   help="how many candidates this one was chosen out of")
    p.add_argument("--selection-rule", required=True,
                   help="why THIS one; 'hand-picked' is an acceptable answer, silence is not")
    p.add_argument("--prediction-id", help="the row id in predictions.csv, if it is one")
    p.add_argument("--dry-run", action="store_true", help="write the .pml, do not ray trace")
    args = p.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    stem = os.path.join(args.outdir, args.out)
    args.png = stem + ".png"
    pml_path = stem + ".pml"
    with open(pml_path, "w") as fh:
        fh.write(build(args))

    prov = {
        "figure": args.out,
        "structure": os.path.abspath(args.structure),
        "reference": os.path.abspath(args.reference) if args.reference else None,
        "prediction_id": args.prediction_id,
        "selected_from": args.selected_from,
        "selection_rule": args.selection_rule,
        "pml": os.path.abspath(pml_path),
        "generated": datetime.datetime.now().isoformat(timespec="seconds"),
    }
    with open(stem + ".prov.json", "w") as fh:
        json.dump(prov, fh, indent=2)

    if args.dry_run:
        print("wrote %s (dry run, not rendered)" % pml_path)
        return 0

    r = subprocess.run(["pymol", "-cq", pml_path],
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    out = r.stdout.decode(errors="replace")
    if r.returncode != 0 or not os.path.exists(args.png):
        sys.stderr.write(out)
        sys.stderr.write("\nrender FAILED\n")
        return 1
    for line in out.splitlines():
        if "Error" in line or "Warning" in line:
            print("  pymol: " + line)
    print("wrote %s" % args.png)
    print("       %s   (edit and re-run to adjust)" % pml_path)
    print("       %s" % (stem + ".prov.json"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
