# generated by render_struct.py on 2026-09-09T19:13:01 -- edit and re-run freely
reinitialize
bg_color white
set ray_opaque_background, 1
set antialias, 2
set orthoscopic, on
set ray_shadows, off
set ray_interior_color, grey70
set cartoon_fancy_helices, 1
set transparency_mode, 2
set specular, 0.15
set cartoon_sampling, 12
set surface_quality, 1
set label_size, 13.0
set label_color, black
set label_font_id, 7
set label_outline_color, white
set label_position, (0, 0, 2.5)
set depth_cue, 0
set ray_trace_mode, 0
set ray_trace_gain, 0.12
set ray_trace_color, grey20

load data/block_a/11_structures/instrument_schematic/3SN6.cif, subject
hide everything
show cartoon, subject and polymer
color 0x9EC4DC, subject and polymer
set cartoon_transparency, 0.4, subject
load data/block_a/11_structures/instrument_schematic/2RH1.cif, refstruct
hide everything, refstruct
show cartoon, refstruct and polymer
color grey60, refstruct and polymer
set cartoon_transparency, 0.45, refstruct
align refstruct and (chain A and polymer and name CA and resi 29-342), subject and (chain R and polymer and name CA and resi 30-342)

# --- ligand and partners in front, fully opaque -------------------------
show sticks, subject and (chain R and resn P0G) and not hydrogens
color 0xD55E00, subject and (chain R and resn P0G) and elem C
util.cnc("subject and (chain R and resn P0G)")
set stick_radius, 0.13, subject and (chain R and resn P0G)


# --- residue labels -------------------------------------------
show sticks, subject and (chain R and resi 75) and sidechain and not hydrogens
label subject and (chain R and resi 75) and name CA, "%s%s" % (oneletter, resi)
set label_position, (-11,-3,6), subject and (chain R and resi 75) and name CA
show sticks, subject and (chain R and resi 275) and sidechain and not hydrogens
label subject and (chain R and resi 275) and name CA, "%s%s" % (oneletter, resi)
set label_position, (8,5,6), subject and (chain R and resi 275) and name CA
show sticks, subject and (chain R and resi 219) and sidechain and not hydrogens
label subject and (chain R and resi 219) and name CA, "%s%s" % (oneletter, resi)
set label_position, (-9,5,6), subject and (chain R and resi 219) and name CA
show sticks, subject and (chain R and resi 326) and sidechain and not hydrogens
label subject and (chain R and resi 326) and name CA, "%s%s" % (oneletter, resi)
set label_position, (9,-6,6), subject and (chain R and resi 326) and name CA
hide cartoon, subject and not (chain R and resi 1-400)
hide cartoon, refstruct and not (chain A and resi 1-400)
hide everything, refstruct and not polymer
show spheres, subject and chain R and resi 75+275 and name CA
color 0x0072B2, subject and chain R and resi 75+275 and name CA
show spheres, refstruct and chain A and resi 75+275 and name CA
color grey40, refstruct and chain A and resi 75+275 and name CA
set sphere_scale, 0.32
distance dtilt_act, subject and chain R and resi 75 and name CA, subject and chain R and resi 275 and name CA
distance dtilt_ina, refstruct and chain A and resi 75 and name CA, refstruct and chain A and resi 275 and name CA
color 0x0072B2, dtilt_act
color grey40, dtilt_ina
set dash_gap, 0.35
set dash_width, 2.5
hide labels, dtilt_act
hide labels, dtilt_ina
set_view (-0.886370, -0.240454, 0.395638, 0.403178, 0.019178, 0.914920, -0.227584, 0.970471, 0.079947, 0.000000, 0.000000, -232.139084, 20.500263, 7.436621, 2.729347, 180.904297, 283.373871, -20.000000)
ray 1500, 1750
png figures/out/ba1a_instrument_schematic.png, dpi=600
