# generated by render_struct.py on 2026-09-09T21:51:45 -- edit and re-run freely
reinitialize
bg_color white
set ray_opaque_background, 1
set antialias, 2
set orthoscopic, on
set ray_shadows, off
set ray_interior_color, grey70
set cartoon_fancy_helices, 1
set transparency_mode, 2
set specular, 0.15
set cartoon_sampling, 12
set surface_quality, 1
set label_size, 16
set label_color, black
set label_font_id, 7
set label_outline_color, white
set label_position, (0, 0, 2.5)
set depth_cue, 0
set ray_trace_mode, 0
set ray_trace_gain, 0.12
set ray_trace_color, grey20

load /Users/aditya/Documents/tools/Novartis_projects/paper/data/block_a/11_structures/connector_orthogonality/4LDE.cif, subject
hide everything
show cartoon, subject and polymer
color 0x9EC4DC, subject and polymer
set cartoon_transparency, 0.38, subject
load /Users/aditya/Documents/tools/Novartis_projects/paper/data/block_a/11_structures/instrument_schematic/2RH1.cif, refstruct
hide everything, refstruct
show cartoon, refstruct and polymer
color grey60, refstruct and polymer
set cartoon_transparency, 0.5, refstruct
align refstruct and (chain A and polymer and name CA and resi 29-342), subject and (chain A and polymer and name CA and resi 1029-1342)

# --- ligand and partners in front, fully opaque -------------------------
show sticks, subject and (chain A and resn P0G) and not hydrogens
color 0xD55E00, subject and (chain A and resn P0G) and elem C
util.cnc("subject and (chain A and resn P0G)")
set stick_radius, 0.13, subject and (chain A and resn P0G)



hide everything, subject and not (chain A and resi 1029-1342)
show cartoon, subject and chain A and resi 1029-1342
hide everything, refstruct and not (chain A and resi 29-342)
show cartoon, refstruct and chain A and resi 29-342
set cartoon_transparency, 0.55, subject
color grey65, subject and polymer
set cartoon_tube_radius, 0.55
create subject_tm6, subject and chain A and resi 1266-1298 and polymer
hide everything, subject_tm6
show cartoon, subject_tm6
cartoon tube, subject_tm6
color 0xD55E00, subject_tm6
set cartoon_transparency, 0, subject_tm6
set cartoon_transparency, 0.62, refstruct
color grey65, refstruct and polymer
set cartoon_tube_radius, 0.55
create refstruct_tm6, refstruct and chain A and resi 266-298 and polymer
hide everything, refstruct_tm6
show cartoon, refstruct_tm6
cartoon tube, refstruct_tm6
color 0x0072B2, refstruct_tm6
set cartoon_transparency, 0, refstruct_tm6
color grey80, refstruct and polymer
set label_distance_digits, 2
show spheres, subject and chain A and resi 1075+1275 and name CA
color 0x000000, subject and chain A and resi 1075+1275 and name CA
show spheres, subject and chain A and resi 1219+1326 and name OH
color 0xCC79A7, subject and chain A and resi 1219+1326 and name OH
show sticks, subject and chain A and resi 1075+1275+1219+1326 and sidechain and not hydrogens
color 0x000000, subject and chain A and resi 1075+1275 and elem C
color 0xCC79A7, subject and chain A and resi 1219+1326 and elem C
set stick_radius, 0.13, subject
set sphere_scale, 0.40
distance d_tilt_subject, subject and chain A and resi 1075 and name CA, subject and chain A and resi 1275 and name CA
distance d_npxxy_subject, subject and chain A and resi 1219 and name OH, subject and chain A and resi 1326 and name OH
color 0x000000, d_tilt_subject
color 0xCC79A7, d_npxxy_subject
set dash_gap, 0.30
set dash_width, 3.0
set label_size, 22
set label_color, black
hide labels, d_tilt_subject
hide labels, d_npxxy_subject
set label_distance_digits, 2
show spheres, refstruct and chain A and resi 75+275 and name CA
color 0x000000, refstruct and chain A and resi 75+275 and name CA
show spheres, refstruct and chain A and resi 219+326 and name OH
color 0xCC79A7, refstruct and chain A and resi 219+326 and name OH
show sticks, refstruct and chain A and resi 75+275+219+326 and sidechain and not hydrogens
color 0x000000, refstruct and chain A and resi 75+275 and elem C
color 0xCC79A7, refstruct and chain A and resi 219+326 and elem C
set stick_radius, 0.13, refstruct
set sphere_scale, 0.40
distance d_tilt_refstruct, refstruct and chain A and resi 75 and name CA, refstruct and chain A and resi 275 and name CA
distance d_npxxy_refstruct, refstruct and chain A and resi 219 and name OH, refstruct and chain A and resi 326 and name OH
color 0x000000, d_tilt_refstruct
color 0xCC79A7, d_npxxy_refstruct
set dash_gap, 0.30
set dash_width, 3.0
set label_size, 22
set label_color, black
hide labels, d_tilt_refstruct
hide labels, d_npxxy_refstruct
set_view (0.214300, -0.120984, 0.969246, -0.960907, 0.151985, 0.231427, -0.175310, -0.980950, -0.083684, 0.000000, 0.000000, -222.235930, -3.973025, -13.907519, -38.581431, 176.577685, 267.894175, -20.000000)
ray 1500, 1650
png /Users/aditya/Documents/tools/Novartis_projects/paper/figures/out/ba1a_instrument_side.png, dpi=600
