# generated by render_struct.py on 2026-09-09T19:24:09 -- edit and re-run freely
reinitialize
bg_color white
set ray_opaque_background, 1
set antialias, 2
set orthoscopic, on
set ray_shadows, off
set ray_interior_color, grey70
set cartoon_fancy_helices, 1
set transparency_mode, 2
set specular, 0.15
set cartoon_sampling, 12
set surface_quality, 1
set label_size, 13.0
set label_color, black
set label_font_id, 7
set label_outline_color, white
set label_position, (0, 0, 2.5)
set depth_cue, 0
set ray_trace_mode, 0
set ray_trace_gain, 0.12
set ray_trace_color, grey20

load data/block_a/11_structures/confidently_wrong/AA2AR__apo__boltz__seed748489558__row567.cif, subject
hide everything
show cartoon, subject and polymer
color 0x9EC4DC, subject and polymer
set cartoon_transparency, 0.4, subject
load data/block_a/11_structures/confidently_wrong/5G53.cif, refstruct
hide everything, refstruct
show cartoon, refstruct and polymer
color grey60, refstruct and polymer
set cartoon_transparency, 0.45, refstruct
align refstruct and (chain A and polymer and name CA and resi 6-312), subject and (chain A and polymer and name CA and resi 6-312)

# --- ligand and partners in front, fully opaque -------------------------
show sticks, subject and (none) and not hydrogens
color 0xD55E00, subject and (none) and elem C
util.cnc("subject and (none)")
set stick_radius, 0.13, subject and (none)


# --- residue labels -------------------------------------------
show sticks, subject and (chain A and resi 48) and sidechain and not hydrogens
label subject and (chain A and resi 48) and name CA, "%s%s" % (oneletter, resi)
set label_position, (-10,-4,6), subject and (chain A and resi 48) and name CA
show sticks, subject and (chain A and resi 235) and sidechain and not hydrogens
label subject and (chain A and resi 235) and name CA, "%s%s" % (oneletter, resi)
set label_position, (9,4,6), subject and (chain A and resi 235) and name CA
show sticks, subject and (chain A and resi 197) and sidechain and not hydrogens
label subject and (chain A and resi 197) and name CA, "%s%s" % (oneletter, resi)
set label_position, (-10,6,6), subject and (chain A and resi 197) and name CA
show sticks, subject and (chain A and resi 288) and sidechain and not hydrogens
label subject and (chain A and resi 288) and name CA, "%s%s" % (oneletter, resi)
set label_position, (10,-6,6), subject and (chain A and resi 288) and name CA
hide cartoon, subject and not (chain A and resi 6-312)
hide cartoon, refstruct and not (chain A and resi 6-312)
hide everything, refstruct and not polymer
show spheres, subject and chain A and resi 48+235 and name CA
color 0x0072B2, subject and chain A and resi 48+235 and name CA
show spheres, refstruct and chain A and resi 48+235 and name CA
color grey40, refstruct and chain A and resi 48+235 and name CA
set sphere_scale, 0.32
distance dtilt_pred, subject and chain A and resi 48 and name CA, subject and chain A and resi 235 and name CA
distance dtilt_ref, refstruct and chain A and resi 48 and name CA, refstruct and chain A and resi 235 and name CA
color 0x0072B2, dtilt_pred
color grey40, dtilt_ref
set dash_gap, 0.35
set dash_width, 2.5
hide labels, dtilt_pred
hide labels, dtilt_ref
set_view (0.396821, -0.192919, 0.897394, 0.395721, 0.918098, 0.022385, -0.828214, 0.346235, 0.440662, 0.000000, 0.000000, -215.879807, 1.574423, 4.611168, 3.966322, 165.969437, 265.790161, -20.000000)
ray 1500, 1600
png figures/out/ba5e_most_confident_apo.png, dpi=600
