# generated by render_struct.py on 2026-09-09T21:52:09 -- edit and re-run freely
reinitialize
bg_color white
set ray_opaque_background, 1
set antialias, 2
set orthoscopic, on
set ray_shadows, off
set ray_interior_color, grey70
set cartoon_fancy_helices, 1
set transparency_mode, 2
set specular, 0.15
set cartoon_sampling, 12
set surface_quality, 1
set label_size, 16
set label_color, black
set label_font_id, 7
set label_outline_color, white
set label_position, (0, 0, 2.5)
set depth_cue, 0
set ray_trace_mode, 0
set ray_trace_gain, 0.12
set ray_trace_color, grey20

load /Users/aditya/Documents/tools/Novartis_projects/paper/data/block_a/11_structures/confidently_wrong/AA2AR__apo__boltz__seed748489558__row567.cif, subject
hide everything
show cartoon, subject and polymer
color grey80, subject and polymer
set cartoon_transparency, 0.48, subject

# --- ligand and partners in front, fully opaque -------------------------
show sticks, subject and (none) and not hydrogens
color 0xD55E00, subject and (none) and elem C
util.cnc("subject and (none)")
set stick_radius, 0.13, subject and (none)



hide everything, subject and not (chain A and resi 1-316)
show cartoon, subject and chain A and resi 1-316
set cartoon_transparency, 0.48, subject
color grey65, subject and polymer
set cartoon_tube_radius, 0.55
create subject_tm6, subject and chain A and resi 226-258 and polymer
hide everything, subject_tm6
show cartoon, subject_tm6
cartoon tube, subject_tm6
color 0x0072B2, subject_tm6
set cartoon_transparency, 0, subject_tm6
set label_distance_digits, 2
show spheres, subject and chain A and resi 48+235 and name CA
color 0x000000, subject and chain A and resi 48+235 and name CA
show spheres, subject and chain A and resi 197+288 and name OH
color 0xCC79A7, subject and chain A and resi 197+288 and name OH
show sticks, subject and chain A and resi 48+235+197+288 and sidechain and not hydrogens
color 0x000000, subject and chain A and resi 48+235 and elem C
color 0xCC79A7, subject and chain A and resi 197+288 and elem C
set stick_radius, 0.13, subject
set sphere_scale, 0.40
distance d_tilt_subject, subject and chain A and resi 48 and name CA, subject and chain A and resi 235 and name CA
distance d_npxxy_subject, subject and chain A and resi 197 and name OH, subject and chain A and resi 288 and name OH
color 0x000000, d_tilt_subject
color 0xCC79A7, d_npxxy_subject
set dash_gap, 0.30
set dash_width, 3.0
set label_size, 22
set label_color, black
hide labels, d_tilt_subject
hide labels, d_npxxy_subject
set_view (-0.467305, 0.162844, 0.868970, -0.386204, -0.921751, -0.034954, 0.795281, -0.351934, 0.493629, 0.000000, 0.000000, -287.063367, 1.502361, 3.675996, 3.190272, 243.171678, 330.955057, -20.000000)
ray 1500, 1750
png /Users/aditya/Documents/tools/Novartis_projects/paper/figures/out/hero_a_apo_alone.png, dpi=600
