# generated by render_struct.py on 2026-09-09T21:52:12 -- edit and re-run freely
reinitialize
bg_color white
set ray_opaque_background, 1
set antialias, 2
set orthoscopic, on
set ray_shadows, off
set ray_interior_color, grey70
set cartoon_fancy_helices, 1
set transparency_mode, 2
set specular, 0.15
set cartoon_sampling, 12
set surface_quality, 1
set label_size, 16
set label_color, black
set label_font_id, 7
set label_outline_color, white
set label_position, (0, 0, 2.5)
set depth_cue, 0
set ray_trace_mode, 0
set ray_trace_gain, 0.12
set ray_trace_color, grey20

load /Users/aditya/Documents/tools/Novartis_projects/paper/data/block_a/11_structures/success_case/DRD2__cognate__of3__seed849213874__row8285.cif, subject
hide everything
show cartoon, subject and polymer
color grey80, subject and polymer
set cartoon_transparency, 0.48, subject

# --- ligand and partners in front, fully opaque -------------------------
show sticks, subject and (none) and not hydrogens
color 0xD55E00, subject and (none) and elem C
util.cnc("subject and (none)")
set stick_radius, 0.13, subject and (none)
# its own object: cartoon_transparency is object-level, so an opaque partner
# in front of a transparent receptor cannot share one object with it
create partner, subject and (chain B and resi 334-354)
hide everything, partner
show cartoon, partner
color 0x009E73, partner
set cartoon_transparency, 0, partner
hide cartoon, subject and (chain B and resi 334-354)



hide everything, subject and chain B
hide everything, subject and not (chain A and resi 30-443)
show cartoon, subject and chain A and resi 30-443
set cartoon_transparency, 0.48, subject
color grey65, subject and polymer
set cartoon_tube_radius, 0.55
create subject_tm6, subject and chain A and resi 366-398 and polymer
hide everything, subject_tm6
show cartoon, subject_tm6
cartoon tube, subject_tm6
color 0xD55E00, subject_tm6
set cartoon_transparency, 0, subject_tm6
color 0x009E73, partner
set cartoon_transparency, 0, partner
set label_distance_digits, 2
show spheres, subject and chain A and resi 76+375 and name CA
color 0x000000, subject and chain A and resi 76+375 and name CA
show spheres, subject and chain A and resi 209+426 and name OH
color 0xCC79A7, subject and chain A and resi 209+426 and name OH
show sticks, subject and chain A and resi 76+375+209+426 and sidechain and not hydrogens
color 0x000000, subject and chain A and resi 76+375 and elem C
color 0xCC79A7, subject and chain A and resi 209+426 and elem C
set stick_radius, 0.13, subject
set sphere_scale, 0.40
distance d_tilt_subject, subject and chain A and resi 76 and name CA, subject and chain A and resi 375 and name CA
distance d_npxxy_subject, subject and chain A and resi 209 and name OH, subject and chain A and resi 426 and name OH
color 0x000000, d_tilt_subject
color 0xCC79A7, d_npxxy_subject
set dash_gap, 0.30
set dash_width, 3.0
set label_size, 22
set label_color, black
hide labels, d_tilt_subject
hide labels, d_npxxy_subject
set_view (0.291505, 0.429910, 0.854519, -0.905743, -0.163265, 0.391118, 0.307659, -0.887987, 0.341796, 0.000000, 0.000000, -313.888523, -2.900184, -13.695758, -12.630956, 260.615167, 367.161879, -20.000000)
ray 1500, 1750
png /Users/aditya/Documents/tools/Novartis_projects/paper/figures/out/hero_b_cognate.png, dpi=600
