#!/usr/bin/env python3
"""Generate paper_tex/refs.bib from lit/refs.bib — the verified bibliography.

lit/refs.bib is canonical. paper_tex/refs.bib is GENERATED; never hand-edit it,
because the next run overwrites it.

Entries with no extraction are emitted with their leading "@" REMOVED, so bibtex
cannot see them at all. Prefixing lines with "%%" is NOT enough: bibtex scans for "@"
anywhere outside an entry and will happily parse "%% @article{...}" as a live entry.
Verified by experiment. Citing one of these must fail loudly at compile time rather
than silently producing a reference nobody has read.
"""
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "lit", "refs.bib")
DST = os.path.join(ROOT, "manuscript", "refs.bib")
NOTES = os.path.join(ROOT, "lit", "notes")

def main():
    raw = open(SRC, encoding="utf-8").read()
    entries, pos = [], 0
    for m in re.finditer(r"^@(\w+)\s*\{\s*([^,\s]+)\s*,", raw, re.M):
        entries.append((m.start(), m.group(2)))
    entries.append((len(raw), None))
    have = {f[:-3] for f in os.listdir(NOTES) if f.endswith(".md")}
    ok, blocked = [], []
    for i in range(len(entries) - 1):
        start, key = entries[i]
        text = raw[start:entries[i + 1][0]].rstrip() + "\n"
        (ok if key in have else blocked).append((key, text))
    with open(DST, "w", encoding="utf-8") as fh:
        fh.write("% refs.bib — GENERATED by analysis/sync_bib.py. DO NOT EDIT.\n")
        fh.write("%% Canonical source: lit/refs.bib\n")
        fh.write(f"%% {len(ok)} citable entries; each has an extraction in lit/notes/.\n")
        fh.write(f"%% {len(blocked)} entries below are COMMENTED OUT: no PDF, no extraction,\n")
        fh.write("%% nobody has read them. Citing one will fail at compile time, on purpose.\n\n")
        for k, t in ok:
            fh.write(t + "\n")
        if blocked:
            fh.write("\n%% ---------- NOT CITABLE: unread, no extraction ----------\n")
            for k, t in blocked:
                fh.write(f"\n%% {k} — never obtained; get the PDF and extract it before citing.\n")
                # strip the leading @ so bibtex cannot parse it; %% alone does NOT work
                for ln in t.strip().splitlines():
                    s = ln.lstrip()
                    fh.write("%% " + (s[1:] if s.startswith("@") else ln) + "\n")
    # keep the Overleaf export copy in step, when that clone exists
    ol = os.path.join(ROOT, "paper_tex", "refs.bib")
    if os.path.isdir(os.path.dirname(ol)):
        import shutil; shutil.copyfile(DST, ol)
    print(f"wrote {DST}")
    print(f"  citable   : {len(ok)}")
    print(f"  commented : {len(blocked)}  ({', '.join(k for k, _ in blocked)})")

if __name__ == "__main__":
    sys.exit(main())
